<?php

/**
 * Client warehouse ingredient master.
 * Loaded by DefaultCatalogService (setup.sh Client Demo Bakery + new org registration).
 *
 * Each row: name, category, unit (gm | ml | pcs). Optional min / stock for demo opening qty.
 * Display names use English (தமிழ்) where Tamil is known.
 */
return [
    // Oil
    ['name' => 'Gold Winner Oil', 'category' => 'oil', 'unit' => 'ml'],
    ['name' => 'Rubini Oil', 'category' => 'oil', 'unit' => 'ml'],
    ['name' => 'Vanaspati 1 Litre (வனஸ்பதி 1 லிட்டர்)', 'category' => 'oil', 'unit' => 'ml'],
    ['name' => 'Vanaspati 1/2 Litre (வனஸ்பதி 1/2 லிட்டர்)', 'category' => 'oil', 'unit' => 'ml'],
    ['name' => 'Sesame Oil', 'category' => 'oil', 'unit' => 'ml'],
    ['name' => 'Groundnut Oil', 'category' => 'oil', 'unit' => 'ml'],
    ['name' => 'Mustard Oil', 'category' => 'oil', 'unit' => 'ml'],
    ['name' => 'Ghee (நெய்)', 'category' => 'oil', 'unit' => 'gm'],
    ['name' => 'Oil Tin', 'category' => 'oil', 'unit' => 'pcs'],
    ['name' => 'Cooking Oil (சமையல் எண்ணெய்)', 'category' => 'oil', 'unit' => 'ml'],
    ['name' => 'Butter (வெண்ணெய்)', 'category' => 'oil', 'unit' => 'gm'],

    // Flour
    ['name' => 'Maida / Wheat Flour (மைதா மாவு)', 'category' => 'flour', 'unit' => 'gm'],
    ['name' => 'Wheat Flour', 'category' => 'flour', 'unit' => 'gm'],
    ['name' => 'Corn Flour (சோள மாவு)', 'category' => 'flour', 'unit' => 'gm'],
    ['name' => 'Besan / Gram Flour (கடலை மாவு)', 'category' => 'flour', 'unit' => 'gm'],
    ['name' => 'Urad Dal Flour', 'category' => 'flour', 'unit' => 'gm'],
    ['name' => 'Ragi Flour (கேழ்வரகு மாவு)', 'category' => 'flour', 'unit' => 'gm'],
    ['name' => 'Cocktail Flour', 'category' => 'flour', 'unit' => 'gm'],
    ['name' => 'Food / Baking Flour', 'category' => 'flour', 'unit' => 'gm'],
    ['name' => 'Flower Spice Mix', 'category' => 'flour', 'unit' => 'gm'],
    ['name' => 'Rice Flour (அரிசி மாவு)', 'category' => 'flour', 'unit' => 'gm'],
    ['name' => 'Rava / Sooji (ரவை)', 'category' => 'flour', 'unit' => 'gm'],

    // Dal / pulses
    ['name' => 'Urad Dal (உளுத்தம் பருப்பு)', 'category' => 'dal', 'unit' => 'gm'],
    ['name' => 'Chana Dal / Split Chickpeas (கடலைப் பருப்பு)', 'category' => 'dal', 'unit' => 'gm'],
    ['name' => 'Moong Dal (பாசிப்பருப்பு)', 'category' => 'dal', 'unit' => 'gm'],
    ['name' => 'Green Gram (பச்சை பயறு)', 'category' => 'dal', 'unit' => 'gm'],
    ['name' => 'Peanut (நிலக்கடலை)', 'category' => 'dal', 'unit' => 'gm'],
    ['name' => 'Roasted Gram', 'category' => 'dal', 'unit' => 'gm'],
    ['name' => 'Chickpeas (கொண்டைக்கடலை)', 'category' => 'dal', 'unit' => 'gm'],
    ['name' => 'Toor Dal (துவரம் பருப்பு)', 'category' => 'dal', 'unit' => 'gm'],
    ['name' => 'Yellow Split Peas (மஞ்சள் பட்டாணி பருப்பு)', 'category' => 'dal', 'unit' => 'gm'],
    ['name' => 'Green Split Peas (பச்சை பட்டாணி பருப்பு)', 'category' => 'dal', 'unit' => 'gm'],
    ['name' => 'Red Lentils (சிவப்பு பருப்பு)', 'category' => 'dal', 'unit' => 'gm'],

    // Nuts & dry fruits
    ['name' => 'Cashew (முந்திரி)', 'category' => 'other', 'unit' => 'gm'],
    ['name' => 'Cashew Bits (முந்திரி துண்டுகள்)', 'category' => 'other', 'unit' => 'gm'],
    ['name' => 'Almond (பாதாம்)', 'category' => 'other', 'unit' => 'gm'],
    ['name' => 'Pistachio (பிஸ்தா)', 'category' => 'other', 'unit' => 'gm'],
    ['name' => 'Walnut (அக்ரோட்)', 'category' => 'other', 'unit' => 'gm'],
    ['name' => 'Raisins (உலர் திராட்சை)', 'category' => 'other', 'unit' => 'gm'],
    ['name' => 'Tutti Frutti (டூட்டி ஃப்ரூட்டி)', 'category' => 'other', 'unit' => 'gm'],
    ['name' => 'Roasted Peanut (வறுத்த நிலக்கடலை)', 'category' => 'other', 'unit' => 'gm'],

    // Spices – whole
    ['name' => 'Cumin', 'category' => 'spice_whole', 'unit' => 'gm'],
    ['name' => 'Fennel', 'category' => 'spice_whole', 'unit' => 'gm'],
    ['name' => 'Black Pepper', 'category' => 'spice_whole', 'unit' => 'gm'],
    ['name' => 'Mustard Seeds', 'category' => 'spice_whole', 'unit' => 'gm'],
    ['name' => 'Fenugreek', 'category' => 'spice_whole', 'unit' => 'gm'],
    ['name' => 'Coriander', 'category' => 'spice_whole', 'unit' => 'gm'],
    ['name' => 'Dry Red Chilli', 'category' => 'spice_whole', 'unit' => 'gm'],
    ['name' => 'Sesame Seeds (எள்)', 'category' => 'spice_whole', 'unit' => 'gm'],
    ['name' => 'Poppy Seeds (கசகசா)', 'category' => 'spice_whole', 'unit' => 'gm'],
    ['name' => 'Cardamom (ஏலக்காய்)', 'category' => 'spice_whole', 'unit' => 'gm'],
    ['name' => 'Cinnamon (பட்டை)', 'category' => 'spice_whole', 'unit' => 'gm'],
    ['name' => 'Clove (கிராம்பு)', 'category' => 'spice_whole', 'unit' => 'gm'],
    ['name' => 'Nutmeg (ஜாதிக்காய்)', 'category' => 'spice_whole', 'unit' => 'gm'],
    ['name' => 'Mace (ஜாதிபத்திரி)', 'category' => 'spice_whole', 'unit' => 'gm'],
    ['name' => 'Dry Ginger (சுக்கு)', 'category' => 'spice_whole', 'unit' => 'gm'],
    ['name' => 'Kalonji (கருஞ்சீரகம்)', 'category' => 'spice_whole', 'unit' => 'gm'],

    // Spice powders / masalas
    ['name' => 'Biryani Masala', 'category' => 'spice_powder', 'unit' => 'gm'],
    ['name' => 'Curry Masala', 'category' => 'spice_powder', 'unit' => 'gm'],
    ['name' => 'Pepper Powder', 'category' => 'spice_powder', 'unit' => 'gm'],
    ['name' => 'Chilli Powder', 'category' => 'spice_powder', 'unit' => 'gm'],
    ['name' => 'Fennel Powder', 'category' => 'spice_powder', 'unit' => 'gm'],
    ['name' => 'Cumin Powder', 'category' => 'spice_powder', 'unit' => 'gm'],
    ['name' => 'Garam Masala', 'category' => 'spice_powder', 'unit' => 'gm'],
    ['name' => 'Sambar Powder', 'category' => 'spice_powder', 'unit' => 'gm'],
    ['name' => 'Mutton Masala', 'category' => 'spice_powder', 'unit' => 'gm'],
    ['name' => 'Chaat Masala', 'category' => 'spice_powder', 'unit' => 'gm'],
    ['name' => 'Asafoetida (Hing)', 'category' => 'spice_powder', 'unit' => 'gm'],

    // Sauces
    ['name' => 'Green Chilli Sauce', 'category' => 'sauce', 'unit' => 'ml'],
    ['name' => 'Red Chilli Sauce', 'category' => 'sauce', 'unit' => 'ml'],
    ['name' => 'Dark Soy Sauce', 'category' => 'sauce', 'unit' => 'ml'],
    ['name' => 'Tomato Sauce 1 kg', 'category' => 'sauce', 'unit' => 'gm'],
    ['name' => 'Tomato Ketchup', 'category' => 'sauce', 'unit' => 'ml'],
    ['name' => 'Vinegar', 'category' => 'sauce', 'unit' => 'ml'],

    // Salt / sweeteners
    ['name' => 'Tata Salt', 'category' => 'salt_sweetener', 'unit' => 'gm'],
    ['name' => 'Soda Salt', 'category' => 'salt_sweetener', 'unit' => 'gm'],
    ['name' => 'Black Salt', 'category' => 'salt_sweetener', 'unit' => 'gm'],
    ['name' => 'White Salt', 'category' => 'salt_sweetener', 'unit' => 'gm'],
    ['name' => 'Jaggery (வெல்லம்)', 'category' => 'salt_sweetener', 'unit' => 'gm'],
    ['name' => 'Sugar (சர்க்கரை)', 'category' => 'salt_sweetener', 'unit' => 'gm'],
    ['name' => 'Icing Sugar (ஐசிங் சர்க்கரை)', 'category' => 'salt_sweetener', 'unit' => 'gm'],
    ['name' => 'Honey (தேன்)', 'category' => 'salt_sweetener', 'unit' => 'gm'],
    ['name' => 'Glucose Syrup (குளுக்கோஸ் சிரப்)', 'category' => 'salt_sweetener', 'unit' => 'gm'],

    // Baking
    ['name' => 'Milk Mix', 'category' => 'baking', 'unit' => 'gm'],
    ['name' => 'Nova Milk Mix', 'category' => 'baking', 'unit' => 'gm'],
    ['name' => 'Milk Flavour', 'category' => 'baking', 'unit' => 'ml'],
    ['name' => 'Milk Powder (பால் பவுடர்)', 'category' => 'baking', 'unit' => 'gm'],
    ['name' => 'Desiccated Coconut (தேங்காய் துருவல்)', 'category' => 'baking', 'unit' => 'gm'],
    ['name' => 'Coconut Powder (தேங்காய் பவுடர்)', 'category' => 'baking', 'unit' => 'gm'],
    ['name' => 'Topping Gel', 'category' => 'baking', 'unit' => 'gm'],
    ['name' => 'Yeast (ஈஸ்ட்)', 'category' => 'baking', 'unit' => 'gm'],
    ['name' => 'Chellam Mixed Jam', 'category' => 'baking', 'unit' => 'gm'],
    ['name' => 'Blue Star Baking Ingredients', 'category' => 'baking', 'unit' => 'gm'],
    ['name' => 'Rose White Essence', 'category' => 'baking', 'unit' => 'ml'],
    ['name' => 'Pineapple Essence', 'category' => 'baking', 'unit' => 'ml'],
    ['name' => 'Vanilla Essence (வெண்ணிலா எசன்ஸ்)', 'category' => 'baking', 'unit' => 'ml'],
    ['name' => 'Water Dough Compound', 'category' => 'baking', 'unit' => 'gm'],
    ['name' => 'Cocoa Powder (கோகோ பவுடர்)', 'category' => 'baking', 'unit' => 'gm'],
    ['name' => 'Milk (பால்)', 'category' => 'baking', 'unit' => 'ml'],
    ['name' => 'Fresh Cream (பிரெஷ் கிரீம்)', 'category' => 'baking', 'unit' => 'ml'],
    ['name' => 'Condensed Milk (கண்டென்ஸ்டு மில்க்)', 'category' => 'baking', 'unit' => 'ml'],
    ['name' => 'Baking Powder (பேக்கிங் பவுடர்)', 'category' => 'baking', 'unit' => 'gm'],
    ['name' => 'Baking Soda (சமையல் சோடா)', 'category' => 'baking', 'unit' => 'gm'],
    ['name' => 'Chocolate Compound (சாக்லேட் காம்பவுண்ட்)', 'category' => 'baking', 'unit' => 'gm'],
    ['name' => 'Chocolate Chips (சாக்லேட் சிப்ஸ்)', 'category' => 'baking', 'unit' => 'gm'],
    ['name' => 'Sprinkles (ஸ்பிரிங்கிள்ஸ்)', 'category' => 'baking', 'unit' => 'gm'],

    // Colours / flavours
    ['name' => 'Lemon Yellow Colour', 'category' => 'colour_flavour', 'unit' => 'gm'],
    ['name' => 'Orange Red Colour', 'category' => 'colour_flavour', 'unit' => 'gm'],
    ['name' => 'Blue Star Asian Pink', 'category' => 'colour_flavour', 'unit' => 'gm'],
    ['name' => 'Blue Star Asian Blue', 'category' => 'colour_flavour', 'unit' => 'gm'],
    ['name' => 'Vanilla Powder (வெண்ணிலா பவுடர்)', 'category' => 'colour_flavour', 'unit' => 'gm'],
    ['name' => 'Orange emulsion essence', 'category' => 'colour_flavour', 'unit' => 'ml'],

    // Other
    ['name' => 'Tamarind', 'category' => 'other', 'unit' => 'gm'],
    ['name' => 'Ajinomoto / MSG', 'category' => 'other', 'unit' => 'gm'],
    ['name' => 'Papad', 'category' => 'other', 'unit' => 'pcs'],
    ['name' => 'Caramel', 'category' => 'other', 'unit' => 'gm'],
    ['name' => 'Egg', 'category' => 'other', 'unit' => 'pcs'],
    ['name' => 'Cake Gel', 'category' => 'baking', 'unit' => 'gm'],
    ['name' => 'Dalda', 'category' => 'oil', 'unit' => 'gm'],
    ['name' => 'Chicken Masala', 'category' => 'spice_powder', 'unit' => 'gm'],
    ['name' => 'Masala Onion', 'category' => 'other', 'unit' => 'gm'],
    ['name' => 'Vegetable', 'category' => 'other', 'unit' => 'gm'],
    ['name' => 'Caramilk', 'category' => 'baking', 'unit' => 'gm'],
    ['name' => 'Grain Grace Dark Chocolate', 'category' => 'baking', 'unit' => 'gm'],
    ['name' => 'Grain Grace White Forest', 'category' => 'baking', 'unit' => 'gm'],
    ['name' => 'Grain Grace Red', 'category' => 'baking', 'unit' => 'gm'],

    // Cake packaging (pcs)
    ['name' => 'Cake Board ½ kg (கேக் போர்டு ½ கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Board 1 kg (கேக் போர்டு 1 கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Board 1½ kg (கேக் போர்டு 1½ கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Board 2 kg (கேக் போர்டு 2 கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Board 3 kg (கேக் போர்டு 3 கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Board 5 kg (கேக் போர்டு 5 கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Card ½ kg (கேக் கார்டு ½ கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Card 1 kg (கேக் கார்டு 1 கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Card 1½ kg (கேக் கார்டு 1½ கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Card 2 kg (கேக் கார்டு 2 கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Card 3 kg (கேக் கார்டு 3 கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Card 5 kg (கேக் கார்டு 5 கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Bottom ½ kg (கேக் பாட்டம் ½ கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Bottom 1 kg (கேக் பாட்டம் 1 கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Bottom 1½ kg (கேக் பாட்டம் 1½ கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Bottom 2 kg (கேக் பாட்டம் 2 கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Bottom 3 kg (கேக் பாட்டம் 3 கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Bottom 5 kg (கேக் பாட்டம் 5 கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Box ½ kg (கேக் பாக்ஸ் ½ கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Box 1 kg (கேக் பாக்ஸ் 1 கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Box 1½ kg (கேக் பாக்ஸ் 1½ கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Box 2 kg (கேக் பாக்ஸ் 2 கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Box 3 kg (கேக் பாக்ஸ் 3 கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],
    ['name' => 'Cake Box 5 kg (கேக் பாக்ஸ் 5 கிலோ)', 'category' => 'cake_packaging', 'unit' => 'pcs'],

    // Food packing covers (pcs)
    ['name' => 'Milk Cover 5 x 7 (பால் கவர் 5 x 7)', 'category' => 'food_packing_covers', 'unit' => 'pcs'],
    ['name' => 'Salna Cover 5 x 7 (சால்னா கவர் 5 x 7)', 'category' => 'food_packing_covers', 'unit' => 'pcs'],
    ['name' => 'Salna Cover 4 x 6 (சால்னா கவர் 4 x 6)', 'category' => 'food_packing_covers', 'unit' => 'pcs'],

    // Carry bags (pcs)
    ['name' => 'Easy Carry Bag 10 x 13 (ஈஸி கேரி பேக் 10 x 13)', 'category' => 'carry_bags', 'unit' => 'pcs'],
    ['name' => 'Easy Carry Bag 13 x 16 (ஈஸி கேரி பேக் 13 x 16)', 'category' => 'carry_bags', 'unit' => 'pcs'],
    ['name' => 'Easy Carry Bag 16 x 20 (ஈஸி கேரி பேக் 16 x 20)', 'category' => 'carry_bags', 'unit' => 'pcs'],
    ['name' => 'Easy Carry Bag 20 x 22 (ஈஸி கேரி பேக் 20 x 22)', 'category' => 'carry_bags', 'unit' => 'pcs'],
    ['name' => 'Easy Carry Bag 24 x 30 (ஈஸி கேரி பேக் 24 x 30)', 'category' => 'carry_bags', 'unit' => 'pcs'],
];
