<?php

/**
 * Sample finished goods using client-pvt ingredients.
 *
 * gm products: recipe qty_per_kg is grams (or ml/pcs) of ingredient per 1 kg finished product
 *   (stored as quantity_required per 1 gm = qty_per_kg / 1000).
 * pcs products: recipe qty is per piece (for puff/roll, qty = 1 kg stuffing batch amounts).
 * bought products: no recipe.
 * qty_pending: true → quantity unknown; quantity_required stored null (INCOMPLETE BOM).
 */
return [
    [
        'number' => '9101',
        'name' => 'Besan Laddu',
        'category' => 'sweet',
        'price' => 400,
        'unit' => 'gm',
        'shelf_life' => 168,
        'source' => 'own',
        'recipe' => [
            ['ingredient' => 'Besan / Gram Flour (கடலை மாவு)', 'qty_per_kg' => 500],
            ['ingredient' => 'Ghee (நெய்)', 'qty_per_kg' => 150],
            ['ingredient' => 'Sugar (சர்க்கரை)', 'qty_per_kg' => 300],
        ],
    ],
    [
        'number' => '9102',
        'name' => 'Garam Masala Mix',
        'category' => 'spices',
        'price' => 350,
        'unit' => 'gm',
        'shelf_life' => 2160,
        'source' => 'own',
        'recipe' => [
            ['ingredient' => 'Cumin', 'qty_per_kg' => 250],
            ['ingredient' => 'Coriander', 'qty_per_kg' => 300],
            ['ingredient' => 'Black Pepper', 'qty_per_kg' => 150],
            ['ingredient' => 'Fennel', 'qty_per_kg' => 150],
            ['ingredient' => 'Dry Red Chilli', 'qty_per_kg' => 150],
        ],
    ],
    [
        'number' => '9103',
        'name' => 'White Bread',
        'category' => 'bread',
        'price' => 40,
        'unit' => 'pcs',
        'shelf_life' => 48,
        'source' => 'own',
        'recipe' => [
            ['ingredient' => 'Maida / Wheat Flour (மைதா மாவு)', 'qty' => 45],
            ['ingredient' => 'Yeast (ஈஸ்ட்)', 'qty' => 2],
            ['ingredient' => 'White Salt', 'qty' => 1],
            ['ingredient' => 'Sugar (சர்க்கரை)', 'qty' => 3],
            ['ingredient' => 'Gold Winner Oil', 'qty' => 5],
        ],
    ],
    [
        'number' => '9104',
        'name' => 'Vanilla Cake',
        'category' => 'bakery',
        'price' => 550,
        'unit' => 'gm',
        'shelf_life' => 48,
        'source' => 'own',
        'recipe' => [
            ['ingredient' => 'Maida / Wheat Flour (மைதா மாவு)', 'qty_per_kg' => 1000],
            ['ingredient' => 'Sugar (சர்க்கரை)', 'qty_per_kg' => 1000],
            ['ingredient' => 'Egg', 'qty_per_kg' => 30],
            ['ingredient' => 'Cake Gel', 'qty_per_kg' => 50],
            ['ingredient' => 'Gold Winner Oil', 'qty_per_kg' => 400],
        ],
    ],
    [
        'number' => '9105',
        'name' => 'Chocolate Cake',
        'category' => 'bakery',
        'price' => 650,
        'unit' => 'gm',
        'shelf_life' => 48,
        'source' => 'own',
        'recipe' => [
            ['ingredient' => 'Maida / Wheat Flour (மைதா மாவு)', 'qty_per_kg' => 1000],
            ['ingredient' => 'Sugar (சர்க்கரை)', 'qty_per_kg' => 1000],
            ['ingredient' => 'Egg', 'qty_per_kg' => 30],
            ['ingredient' => 'Cake Gel', 'qty_per_kg' => 50],
            ['ingredient' => 'Gold Winner Oil', 'qty_per_kg' => 400],
            ['ingredient' => 'Caramilk', 'qty_pending' => true],
        ],
    ],
    [
        'number' => '9106',
        'name' => 'Salt Biscuit',
        'category' => 'biscuit',
        'price' => 10,
        'unit' => 'pcs',
        'shelf_life' => 336,
        'source' => 'own',
        'recipe' => [
            ['ingredient' => 'Maida / Wheat Flour (மைதா மாவு)', 'qty' => 30],
            ['ingredient' => 'White Salt', 'qty' => 1],
            ['ingredient' => 'Ghee (நெய்)', 'qty' => 8],
            ['ingredient' => 'Sugar (சர்க்கரை)', 'qty' => 5],
        ],
    ],
    [
        'number' => '9107',
        'name' => 'Coconut Biscuit',
        'category' => 'biscuit',
        'price' => 12,
        'unit' => 'pcs',
        'shelf_life' => 336,
        'source' => 'own',
        'recipe' => [
            ['ingredient' => 'Maida / Wheat Flour (மைதா மாவு)', 'qty' => 28],
            ['ingredient' => 'Sugar (சர்க்கரை)', 'qty' => 12],
            ['ingredient' => 'Ghee (நெய்)', 'qty' => 10],
            ['ingredient' => 'Coconut Powder (தேங்காய் பவுடர்)', 'qty' => 8],
            ['ingredient' => 'Vanilla Essence (வெண்ணிலா எசன்ஸ்)', 'qty' => 1],
        ],
    ],
    [
        'number' => '9108',
        'name' => 'Mixed Jam',
        'category' => 'other',
        'price' => 80,
        'unit' => 'gm',
        'shelf_life' => null,
        'source' => 'bought',
        'recipe' => [],
    ],

    // --- Bakery production BOMs ---
    [
        'number' => '9201',
        'name' => 'Bun',
        'category' => 'bread',
        'price' => 15,
        'unit' => 'gm',
        'shelf_life' => 48,
        'source' => 'own',
        'aliases' => ['Normal Bun', 'Bun'],
        'recipe' => [
            ['ingredient' => 'Maida / Wheat Flour (மைதா மாவு)', 'qty_per_kg' => 1000],
            ['ingredient' => 'White Salt', 'qty_per_kg' => 10],
            ['ingredient' => 'Sugar (சர்க்கரை)', 'qty_per_kg' => 300],
            ['ingredient' => 'Gold Winner Oil', 'qty_per_kg' => 100],
            ['ingredient' => 'Yeast (ஈஸ்ட்)', 'qty_per_kg' => 15],
        ],
    ],
    [
        'number' => '9202',
        'name' => 'Veg Puff',
        'category' => 'bakery',
        'price' => 25,
        'unit' => 'pcs',
        'shelf_life' => 24,
        'source' => 'own',
        'aliases' => ['Veg puff', 'Veg Puff'],
        'recipe' => [
            ['ingredient' => 'Maida / Wheat Flour (மைதா மாவு)', 'qty' => 1000],
            ['ingredient' => 'White Salt', 'qty' => 15],
            ['ingredient' => 'Sugar (சர்க்கரை)', 'qty' => 50],
            ['ingredient' => 'Dalda', 'qty' => 50],
            ['ingredient' => 'Masala Onion', 'qty_pending' => true],
            ['ingredient' => 'Vegetable', 'qty_pending' => true],
            ['ingredient' => 'Chilli Powder', 'qty' => 25],
            ['ingredient' => 'Chicken Masala', 'qty' => 25],
            ['ingredient' => 'Egg', 'qty' => 3],
        ],
    ],
    [
        'number' => '9203',
        'name' => 'Egg Puff',
        'category' => 'bakery',
        'price' => 30,
        'unit' => 'pcs',
        'shelf_life' => 24,
        'source' => 'own',
        'recipe' => [
            ['ingredient' => 'Maida / Wheat Flour (மைதா மாவு)', 'qty' => 1000],
            ['ingredient' => 'White Salt', 'qty' => 15],
            ['ingredient' => 'Sugar (சர்க்கரை)', 'qty' => 50],
            ['ingredient' => 'Dalda', 'qty' => 50],
            ['ingredient' => 'Masala Onion', 'qty_pending' => true],
            ['ingredient' => 'Vegetable', 'qty_pending' => true],
            ['ingredient' => 'Chilli Powder', 'qty' => 25],
            ['ingredient' => 'Chicken Masala', 'qty' => 25],
            ['ingredient' => 'Egg', 'qty' => 3],
        ],
    ],
    [
        'number' => '9204',
        'name' => 'Chicken Puff',
        'category' => 'bakery',
        'price' => 35,
        'unit' => 'pcs',
        'shelf_life' => 24,
        'source' => 'own',
        'recipe' => [
            ['ingredient' => 'Maida / Wheat Flour (மைதா மாவு)', 'qty' => 1000],
            ['ingredient' => 'White Salt', 'qty' => 15],
            ['ingredient' => 'Sugar (சர்க்கரை)', 'qty' => 50],
            ['ingredient' => 'Dalda', 'qty' => 50],
            ['ingredient' => 'Masala Onion', 'qty_pending' => true],
            ['ingredient' => 'Vegetable', 'qty_pending' => true],
            ['ingredient' => 'Chilli Powder', 'qty' => 25],
            ['ingredient' => 'Chicken Masala', 'qty' => 25],
            ['ingredient' => 'Egg', 'qty' => 3],
        ],
    ],
    [
        'number' => '9205',
        'name' => 'Chicken Roll',
        'category' => 'bakery',
        'price' => 40,
        'unit' => 'pcs',
        'shelf_life' => 24,
        'source' => 'own',
        'recipe' => [
            ['ingredient' => 'Maida / Wheat Flour (மைதா மாவு)', 'qty' => 1000],
            ['ingredient' => 'White Salt', 'qty' => 15],
            ['ingredient' => 'Sugar (சர்க்கரை)', 'qty' => 50],
            ['ingredient' => 'Dalda', 'qty' => 50],
            ['ingredient' => 'Masala Onion', 'qty_pending' => true],
            ['ingredient' => 'Vegetable', 'qty_pending' => true],
            ['ingredient' => 'Chilli Powder', 'qty' => 25],
            ['ingredient' => 'Chicken Masala', 'qty' => 25],
            ['ingredient' => 'Egg', 'qty' => 3],
        ],
    ],
    [
        'number' => '9206',
        'name' => 'Veg Roll',
        'category' => 'bakery',
        'price' => 30,
        'unit' => 'pcs',
        'shelf_life' => 24,
        'source' => 'own',
        'recipe' => [
            ['ingredient' => 'Maida / Wheat Flour (மைதா மாவு)', 'qty' => 1000],
            ['ingredient' => 'White Salt', 'qty' => 15],
            ['ingredient' => 'Sugar (சர்க்கரை)', 'qty' => 50],
            ['ingredient' => 'Dalda', 'qty' => 50],
            ['ingredient' => 'Masala Onion', 'qty_pending' => true],
            ['ingredient' => 'Vegetable', 'qty_pending' => true],
            ['ingredient' => 'Chilli Powder', 'qty' => 25],
            ['ingredient' => 'Chicken Masala', 'qty' => 25],
            ['ingredient' => 'Egg', 'qty' => 3],
        ],
    ],
    [
        'number' => '9207',
        'name' => 'Honey Cake',
        'category' => 'bakery',
        'price' => 600,
        'unit' => 'gm',
        'shelf_life' => 48,
        'source' => 'own',
        'recipe' => [
            ['ingredient' => 'Maida / Wheat Flour (மைதா மாவு)', 'qty_per_kg' => 1000],
            ['ingredient' => 'Sugar (சர்க்கரை)', 'qty_per_kg' => 1000],
            ['ingredient' => 'Egg', 'qty_per_kg' => 30],
            ['ingredient' => 'Cake Gel', 'qty_per_kg' => 50],
            ['ingredient' => 'Gold Winner Oil', 'qty_per_kg' => 400],
            ['ingredient' => 'Orange emulsion essence', 'qty_pending' => true],
        ],
    ],
    [
        'number' => '9208',
        'name' => 'Black Forest Cake',
        'category' => 'bakery',
        'price' => 800,
        'unit' => 'gm',
        'shelf_life' => 48,
        'source' => 'own',
        'recipe' => [
            ['ingredient' => 'Grain Grace Dark Chocolate', 'qty_pending' => true],
            ['ingredient' => 'Egg', 'qty_per_kg' => 12],
            ['ingredient' => 'Gold Winner Oil', 'qty_per_kg' => 100],
            ['ingredient' => 'Cake Gel', 'qty_per_kg' => 15],
        ],
    ],
    [
        'number' => '9209',
        'name' => 'White Forest Cake',
        'category' => 'bakery',
        'price' => 800,
        'unit' => 'gm',
        'shelf_life' => 48,
        'source' => 'own',
        'recipe' => [
            ['ingredient' => 'Grain Grace White Forest', 'qty_pending' => true],
            ['ingredient' => 'Egg', 'qty_per_kg' => 14],
            ['ingredient' => 'Gold Winner Oil', 'qty_per_kg' => 100],
            ['ingredient' => 'Cake Gel', 'qty_per_kg' => 15],
        ],
    ],
    [
        'number' => '9210',
        'name' => 'Red Velvet Cake',
        'category' => 'bakery',
        'price' => 850,
        'unit' => 'gm',
        'shelf_life' => 48,
        'source' => 'own',
        'recipe' => [
            ['ingredient' => 'Grain Grace Red', 'qty_pending' => true],
            ['ingredient' => 'Egg', 'qty_per_kg' => 14],
            ['ingredient' => 'Gold Winner Oil', 'qty_per_kg' => 100],
            ['ingredient' => 'Cake Gel', 'qty_per_kg' => 15],
        ],
    ],
    [
        'number' => '9211',
        'name' => 'Madakku Bun',
        'category' => 'bread',
        'price' => 20,
        'unit' => 'gm',
        'shelf_life' => 48,
        'source' => 'own',
        'recipe' => [
            ['ingredient' => 'Maida / Wheat Flour (மைதா மாவு)', 'qty_per_kg' => 1000],
            ['ingredient' => 'Sugar (சர்க்கரை)', 'qty_per_kg' => 300],
        ],
    ],
    [
        'number' => '9212',
        'name' => 'Butter Bun',
        'category' => 'bread',
        'price' => 25,
        'unit' => 'gm',
        'shelf_life' => 48,
        'source' => 'own',
        'recipe' => [
            ['ingredient' => 'Maida / Wheat Flour (மைதா மாவு)', 'qty_per_kg' => 1000],
            ['ingredient' => 'Sugar (சர்க்கரை)', 'qty_per_kg' => 300],
            ['ingredient' => 'Butter (வெண்ணெய்)', 'qty_pending' => true],
        ],
    ],
    [
        'number' => '9213',
        'name' => 'Fruit Bun',
        'category' => 'bread',
        'price' => 25,
        'unit' => 'gm',
        'shelf_life' => 48,
        'source' => 'own',
        'recipe' => [
            ['ingredient' => 'Maida / Wheat Flour (மைதா மாவு)', 'qty_per_kg' => 1000],
            ['ingredient' => 'Sugar (சர்க்கரை)', 'qty_per_kg' => 300],
            ['ingredient' => 'Tutti Frutti (டூட்டி ஃப்ரூட்டி)', 'qty_pending' => true],
        ],
    ],
    [
        'number' => '9214',
        'name' => 'Jam Bun',
        'category' => 'bread',
        'price' => 25,
        'unit' => 'gm',
        'shelf_life' => 48,
        'source' => 'own',
        'recipe' => [
            ['ingredient' => 'Maida / Wheat Flour (மைதா மாவு)', 'qty_per_kg' => 1000],
            ['ingredient' => 'Sugar (சர்க்கரை)', 'qty_per_kg' => 300],
            ['ingredient' => 'Chellam Mixed Jam', 'qty_pending' => true],
        ],
    ],
];
